settings:
  title: 'Status Page'
  url: 'https://status.newsdesk.cloud' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: al-ain-com # unique identifier
    name: al-ain.com
    description: 'al-ain.com.' # default=empty
    url: 'https://al-ain.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: api-al-ain.net
    name: api-al-ain.net
    description: 'Alain API.'
    url: 'https://api.al-ain.net'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

    - id: newsdesk-cloud
    name: newsdesc.cloud
    description: 'Newsdesc.'
    url: 'https://newsdesc.cloud'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
